### ISSUE TITLE
How to do MLM for AAV dataset?

### ISSUE THREAD

**Issue by mostafakarimi71** [vishakhpk/iter-extrapolation#3]
Thanks for the great paper!

I am wondering if you can share the code which you used to create Mutations through MLM for AAV task?

**Comment by mostafakarimi71** [comment]
Or maybe you can provide the pairs created for AAV/ACE/Sentiments to train the generative model for better reproducibility?

**Comment by vishakhpk** [comment]
Apologies! Mutations for AAV happen the [same way](https://github.com/vishakhpk/iter-extrapolation/blob/main/ace2/mlm_mutation.py) as with ACE2 but with the corresponding wild type. While I clean up that script, I've updated the training sequences on ACE2 and AAV as tarballs here which would let you directly train the generator 9416272

**Comment by mostafakarimi71** [comment]
That is awesome! Thank you very much! I am wondering if you can provide the same data for sentiments as well? Also, I would really appreciate it if you can share the final checkpoints of your seq2seq model for the three tasks.
